# Generated by Django 3.2.4 on 2021-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20210613_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='room_no',
            field=models.CharField(max_length=100),
        ),
    ]
